/// Flutter icons MyFlutterApp
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData search = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_woman = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_pair = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video_alt = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocam = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData videocam_alt = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_list = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circle = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_up = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thumbs_down = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_icon = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_alt = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData print = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attention = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData question = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData article = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData article_alt = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrench = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket_alt = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_alt = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_off = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_down = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bullhorn = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock_alt = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_full = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_small = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_in = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zoom_out = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData popup = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_dir = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_dir = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_dir = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_dir = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cw = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award_1 = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile_alt = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablet = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ipod = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cd = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grid = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData easel = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_pie = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData at = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData colon = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData semicolon = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData squares = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xf300, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_rect = IconData(0xf301, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xf302, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_bird = IconData(0xf303, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter_rect = IconData(0xf314, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xf315, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award = IconData(0xf559, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
